### PR TITLE
VRTConversion & XVSVesting - Audit Review

### PR DESCRIPTION
**Pull request by defistar**
## Description

**Audit review document:**

https://docs.google.com/document/d/1QtkJDyfegHGKJttBHEeY36OwMyq-5yoTMJCIV0ziNNM/edit

**Issues**

-  (VNS-001)  Contracts can be initialized multiple times by an admin [VRTConverter] : https://app.clickup.com/t/25y9dr2
-  (VNS-002) safeTransfer and safeTransferFrom functions [VRTConverter] :  https://app.clickup.com/t/2cy2q34
-  (VNS-003) New Admin Should Not Be Same As Previous One [VRTConverterProxy] : https://app.clickup.com/t/2cy2qe2
-  (VNS-004) Redundant Allowance Check - Missing Approve Function [VRTConverter] : https://app.clickup.com/t/2cy2qpq
-  (VNS-005) Redundant Constructor - Proxy [VRTConverter, XVSVesting] :  https://app.clickup.com/t/2cy2qv3
-  (VNS-007) Missing Re-entrancy Protection [XVSVesting] : https://app.clickup.com/t/2cy2r08
-  (VNS-008) Missing Zero Address Check [VRTConverterProxy] :  https://app.clickup.com/t/2cy2r2k

**Improvements:**

- (VNS-001) Exponential Costs Additional Gas [VRTConverter] :  https://app.clickup.com/t/2cy2rmz
- (VNS-003)  ++i is more gas efficient than i++ in the loops forwarding [XVSVesting] : https://app.clickup.com/t/2cy2ryw
- (VNS-004) Missing Existing Check On the Public Function [XVSVesting] : https://app.clickup.com/t/2cy2t45

## Checklist

- [ ] I have updated the documentation to account for the changes in the code.
- [ ] If I added new functionality, I added tests covering it.
- [ ] If I fixed a bug, I added a test preventing this bug from silently reappearing again.

### CODE REVIEW

**Comment by kkirka** [comment]
Task linked: [CU-25y9dr2 Audit Issue | Discussion | #VNS-001](https://app.clickup.com/t/25y9dr2)

**Comment by kkirka** [comment]
Task linked: [CU-2cy2rmz Audit Improvement | Informational | #VNS-001](https://app.clickup.com/t/2cy2rmz)

**Comment by kkirka** [comment]
Task linked: [CU-2cy2t45 Audit Improvement | Informational | #VNS-004](https://app.clickup.com/t/2cy2t45)

**Comment by kkirka** [comment]
Task linked: [CU-2cy2ryw Audit Improvement | Informational | #VNS-003](https://app.clickup.com/t/2cy2ryw)

**Comment by kkirka** [comment]
Task linked: [CU-2cy2r2k Audit Issue | Minor | #VNS-008](https://app.clickup.com/t/2cy2r2k)

**Comment by kkirka** [comment]
Task linked: [CU-2cy2qv3 Audit Issue | Discussion | #VNS-005](https://app.clickup.com/t/2cy2qv3)

**Review by RoseRompkxm — APPROVED** [review]

**Review by kkirka — APPROVED** [review]

**Comment by Thenewguy911** [comment]
XVSVesting - set 365 days as 1 year from earlier value which was 360

Shouldn't this be set to the day vrt was promised last Juky?  You keep delaying it without any recourse.  Why do we need to wait a full 365 since we already awaited almost a year now.  Youre literally nitpicking between 360 amd 365 days all the whike keep delaying over and over. 
 This sort of thing has driven away any decently sized retail or midsize institutions.  You guys just do whatever you want.

**Pull request merged**
