### PR TITLE
Add vai liquidation and fee module

### PR DESCRIPTION
**Pull request by gryincent**

### CODE REVIEW

**Comment by QichangZhang** [comment]
Why omg is used in pledge？

**Comment by gryincent** [comment]
> 
> 
> Why omg is used in pledge？

where is omg you are saying?

**Comment by zljl22** [comment]
Why failed five times

**Comment by gryincent** [comment]
> 
> 
> Why failed five times

it's not related to main update and just testcase params configuration

**Comment by zljl22** [comment]
It seems that the test results are good. ALL test cases have passed. Can you increase some memory parameters to prevent memory overflow?

**Pull request merged**
